/**
 * tokens:import — W3C DTCG JSON → CSS variable blocks.
 *
 * Interchange importer: when a DTCG file arrives from Figma (Tokens Studio),
 * a platform team, or a design hand-off, this tool converts it into the
 * `:root` / `.dark` variable blocks that can be merged into
 * styles/globals.css (the source of truth). It is NOT part of the normal
 * build — globals.css is hand-edited.
 *
 * Usage: bun run tokens:import -- <path/to/tokens.json> [output.css]
 *   - `-dark` suffixed tokens  → emitted as fixed `--pv-…-dark` variables
 *   - other tokens             → emitted as `--pv-…` variables
 *   - `{alias}` references     → resolved within the file (cycles rejected)
 */
import { readFileSync, writeFileSync } from "node:fs";

const input = process.argv[2];
const output = process.argv[3] ?? "/tmp/phanvic-dtcg-import.css";

if (!input) {
  console.error("Usage: bun run tokens:import -- <tokens.json> [output.css]");
  process.exit(1);
}

interface TokenNode {
  $value?: string | number;
  $type?: string;
  [key: string]: unknown;
}

const raw = JSON.parse(readFileSync(input, "utf8"));

const resolved: Array<{ cssVar: string; value: string; isDark: boolean }> = [];
const all: Record<string, unknown> = {};

function getByPath(obj: unknown, pathStr: string): TokenNode | undefined {
  let curr: unknown = obj;
  for (const part of pathStr.split(".")) {
    if (curr == null || typeof curr !== "object") return undefined;
    curr = (curr as Record<string, unknown>)[part];
  }
  return curr as TokenNode | undefined;
}

function resolveValue(val: unknown, seen = new Set<string>()): unknown {
  if (typeof val !== "string") return val;
  const m = val.match(/^\{([\w.-]+)\}$/);
  if (!m) return val;
  if (seen.has(m[1])) throw new Error(`Circular alias: ${m[1]}`);
  seen.add(m[1]);
  const target = getByPath(all, m[1]);
  if (!target) throw new Error(`Alias target not found: ${m[1]}`);
  return resolveValue(target.$value !== undefined ? target.$value : target, seen);
}

function traverse(obj: unknown, path: string[] = []) {
  if (!obj || typeof obj !== "object") return;
  const node = obj as Record<string, unknown>;
  if (node.$value !== undefined) {
    const key = path.join("-");
    const value = String(resolveValue(node.$value));
    resolved.push({
      cssVar: `--ds-${key}`,
      value,
      isDark: path[path.length - 1].endsWith("-dark"),
    });
    return;
  }
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith("$")) continue;
    traverse(v, [...path, k]);
  }
}
traverse(raw);

const light: string[] = [];
const dark: string[] = [];
for (const token of resolved) {
  if (token.isDark) {
    dark.push(`  ${token.cssVar}: ${token.value};`);
  } else {
    light.push(`  ${token.cssVar}: ${token.value};`);
  }
}

const css = `/* Generated by scripts/dtcg-to-css.ts from ${input} — DO NOT EDIT.
   Review and merge these blocks into styles/globals.css. */

:root {
${light.join("\n")}
}

.dark {
${dark.join("\n")}
}
`;

writeFileSync(output, css);
console.log(`Wrote ${output} (${resolved.length} tokens)`);
