/**
 * Generates the pre-built utility stylesheets for the component packages:
 *
 *   1. packages/ui/styles.css          — published as `@design-system/ui/styles.css`
 *   2. packages/content-ui/styles.css  — published as
 *                                        `@design-system/content-ui/styles.css`
 *   3. packages/design-tokens/styles/utilities.css — legacy union of (1)+(2),
 *      re-exported through `@design-system/tokens/styles/index.css`.
 *
 * Each package owns the utilities for its own component sources; a consumer
 * imports the stylesheets of the packages it uses. The legacy union keeps
 * `index.css` consumers (which import tokens + utilities in one entry)
 * working unchanged.
 *
 * Why this exists: component className strings only become CSS when the
 * Tailwind engine scans them. Bundler dev servers (Turbopack) scope that
 * scan to the app package and cannot reach this design system, so the
 * utilities are pre-generated here and imported by consumers as a plain
 * stylesheet.
 *
 * Post-processing:
 *  1. strips the :root/.dark variable blocks (tokens.css — the value source
 *     of truth — is imported separately by consumers);
 *  2. wraps everything in `@layer utilities`;
 *  3. prepends the cascade layer order statement.
 *
 * Run: bun run generate:styles
 */
import { spawnSync } from "node:child_process";
import { readFileSync, rmSync, writeFileSync } from "node:fs";

const RAW_DIR = "/tmp/ds-styles";

const droppedSelectorPrefixes = new Set([":root", ".dark"]);

/** Runs Tailwind on one entry stylesheet and returns the inner utilities body
 *  (everything that belongs inside `@layer utilities { … }`). */
const compileBody = (entry: string): string => {
  const name = entry.split("/").pop()!.replace(/\.css$/, "");
  const rawOutput = `${RAW_DIR}/${name}.raw.css`;
  const proc = spawnSync(
    "bunx",
    ["@tailwindcss/cli", "-i", entry, "-o", rawOutput],
    { stdio: "pipe" },
  );
  if (proc.status !== 0) {
    console.error(proc.stderr.toString());
    process.exit(proc.status ?? 1);
  }
  const raw = readFileSync(rawOutput, "utf8");

  let body = "";
  let i = 0;
  while (i < raw.length) {
    const braceIndex = raw.indexOf("{", i);

    if (braceIndex === -1) {
      body += raw.slice(i);
      break;
    }

    // Selector text between the previous block end and this brace.
    let selectorStart = i;
    const priorSemicolon = raw.lastIndexOf(";", braceIndex);
    if (priorSemicolon > selectorStart) {
      selectorStart = priorSemicolon + 1;
    }
    const selector = raw.slice(selectorStart, braceIndex).trim();

    // Find the matching closing brace.
    let depth = 1;
    let cursor = braceIndex + 1;
    while (cursor < raw.length && depth > 0) {
      if (raw[cursor] === "{") depth += 1;
      else if (raw[cursor] === "}") depth -= 1;
      cursor += 1;
    }

    const shouldDrop =
      !selector.includes("{") &&
      (droppedSelectorPrefixes.has(selector) ||
        selector === ":root, :host" ||
        selector === "@layer properties");

    if (!shouldDrop) {
      body += raw.slice(i, cursor);
    }

    i = cursor;
  }
  return body;
};

const HEADER = `/* ! @design-system utilities — GENERATED by scripts/generate-styles.ts.
   Do not edit. Token values come from @design-system/tokens styles/tokens.css,
   which consumers import separately. */
`;

const wrap = (body: string): string =>
  `${HEADER}@layer theme, base, components, utilities;\n\n@layer utilities {\n${body}}\n`;

rmSync(RAW_DIR, { force: true, recursive: true });
const uiBody = compileBody("./scripts/styles-entry-ui.css");
const contentUiBody = compileBody("./scripts/styles-entry-content-ui.css");

const outputs: Array<[string, string]> = [
  ["./packages/ui/styles.css", wrap(uiBody)],
  ["./packages/content-ui/styles.css", wrap(contentUiBody)],
  // Legacy union: keeps `@design-system/tokens/styles/index.css` consumers
  // working with a single import.
  ["./packages/design-tokens/styles/utilities.css", wrap(uiBody + contentUiBody)],
];

for (const [output, css] of outputs) {
  writeFileSync(output, css);
  console.log(`Generated ${output} (${(css.length / 1024).toFixed(1)} kB)`);
}
rmSync(RAW_DIR, { force: true, recursive: true });
