/**
 * Generates packages/design-tokens/styles/utilities.css — the Tailwind utilities referenced by the
 * @design-system/ui and @design-system/content-ui component sources.
 *
 * Why this exists: component className strings only become CSS when the
 * Tailwind engine scans them. Bundler dev servers (Turbopack) scope that
 * scan to the app package and cannot reach this design system, so the
 * utilities are pre-generated here and imported by consumers as a plain
 * stylesheet.
 *
 * Post-processing:
 *  1. strips the :root/.dark variable blocks (styles/globals.css — the
 *     source of truth — is imported separately by consumers);
 *  2. wraps everything in `@layer utilities`;
 *  3. prepends the cascade layer order statement.
 *
 * Run: bun run generate:styles
 */
import { spawnSync } from "node:child_process";
import { readFileSync, rmSync, writeFileSync } from "node:fs";

const RAW_OUTPUT = "/tmp/ds-styles.raw.css";
const OUT = "./packages/design-tokens/styles/utilities.css";

const proc = spawnSync(
  "bunx",
  ["@tailwindcss/cli", "-i", "./scripts/styles-entry.css", "-o", RAW_OUTPUT],
  { stdio: "pipe" },
);

if (proc.status !== 0) {
  console.error(proc.stderr.toString());
  process.exit(proc.status ?? 1);
}

const raw = readFileSync(RAW_OUTPUT, "utf8");

const droppedSelectorPrefixes = new Set([":root", ".dark"]);
let body = "";
let i = 0;

while (i < raw.length) {
  const braceIndex = raw.indexOf("{", i);

  if (braceIndex === -1) {
    body += raw.slice(i);
    break;
  }

  // Selector text between the previous block end and this brace.
  let selectorStart = i;
  const priorSemicolon = raw.lastIndexOf(";", braceIndex);
  if (priorSemicolon > selectorStart) {
    selectorStart = priorSemicolon + 1;
  }
  const selector = raw.slice(selectorStart, braceIndex).trim();

  // Find the matching closing brace.
  let depth = 1;
  let cursor = braceIndex + 1;
  while (cursor < raw.length && depth > 0) {
    if (raw[cursor] === "{") depth += 1;
    else if (raw[cursor] === "}") depth -= 1;
    cursor += 1;
  }

  const shouldDrop =
    !selector.includes("{") &&
    (droppedSelectorPrefixes.has(selector) ||
      selector === ":root, :host" ||
      selector === "@layer properties");

  if (!shouldDrop) {
    body += raw.slice(i, cursor);
  }

  i = cursor;
}

const stylesCss = `/* ! @design-system/ui utilities — GENERATED by scripts/generate-styles.ts.
   Do not edit. The token source of truth is packages/design-tokens/styles/tokens.css, which
   consumers import separately. */
@layer theme, base, components, utilities;

@layer utilities {
${body}
}
`;

writeFileSync(OUT, stylesCss);
rmSync(RAW_OUTPUT, { force: true });
console.log(`Generated ${OUT} (${(stylesCss.length / 1024).toFixed(1)} kB)`);
